algoritmo "Imprimir pares 2.0"
// Função : imprimir numeros pares de acordo com a entrada do usuario
// Autor :Marina
// Data : 04/09/2023
// Seção de Declarações 
var

   i, num: inteiro

inicio

   escreval("------------------------Números pares---------------------------")
   escreva("Digite um numero inteiro: ")
   leia(num)
   escreval()
   i <- 0
   enquanto (i <= num) faca
      escreval(i)
      i <- i+2
   fimenquanto
fimalgoritmo
