algoritmo "contadorRegressivo"
// Função : Criar um contador regressivo de passo -1
// Autor :Marina
// Data : 25/09/2023
// Seção de Declarações 
var

   n1: inteiro

inicio

   escreval("===================== Contador regressivo =======================")
   escreval()
   escreva("Digite o numero inicial: ")
   leia(n1)
   
   enquanto n1 >= 0 faca
   
      escreval(n1)
      n1 <- n1-1
   
   fimenquanto

fimalgoritmo
