algoritmo "PositoNegativo"
// Função : Crie um algortimo que determine se um numero é positivo ou negativo
// Autor : Marina
// Data : 28/08/2023
// Seção de Declarações 
var
   x: inteiro

inicio
   escreval("---------------------Numero positivo ou negativo---------------------")
   escreval()
   escreva("Por favor, digite um numero: ")
   leia(x)
   se x >=0 entao
      escreval("O numero ",x, " e positivo")
   senao
      escreval("O numero ",x, " e negativo")
   fimse

fimalgoritmo
